# Generated by Django 6.0.7 on 2026-07-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='calls.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_data', models.JSONField(help_text='Stores: customer_name, primary_intent, most_asked_question, ai_failure_point')),
                ('needs_followup', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='calls.callsession')),
            ],
        ),
    ]
