# Generated by Django 5.2.16 on 2026-07-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_callqueueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='callqueueitem',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callqueueitem',
            name='call_duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callqueueitem',
            name='top_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callqueueitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='callqueueitem',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callqueueitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='callqueueitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CALLED', 'Called'), ('FOLLOW_UP', 'Follow Up')], default='PENDING', max_length=20),
        ),
    ]
