# Generated by Django 5.2.16 on 2026-07-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_callqueueitem_ai_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Brainex AI Solution', max_length=100)),
                ('bot_name', models.CharField(default='Alex', max_length=50)),
                ('opening_greeting', models.TextField(default='Hello! This is Alex from Brainex AI. How can I assist you today?')),
                ('closing_statement', models.TextField(default='Thank you for contacting Brainex AI. Have a great day ahead! Goodbye.')),
                ('company_details', models.TextField(help_text='Enter pricing, services, working hours, FAQs, etc.')),
                ('is_active', models.BooleanField(default=True, help_text='Set as the active voice prompt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
