# Generated by Django 5.2.16 on 2026-08-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_companyscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to='call_recordings/'),
        ),
        migrations.AlterField(
            model_name='callqueueitem',
            name='details',
            field=models.TextField(blank=True, help_text='Context or objective for AI Co-Pilot', null=True),
        ),
    ]
