# Generated by Django 5.2.16 on 2026-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_callsession_recording_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='ai_recording_file',
            field=models.FileField(blank=True, help_text='AI response audio', null=True, upload_to='ai_recordings/'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='recording_file',
            field=models.FileField(blank=True, help_text='Customer voice audio', null=True, upload_to='call_recordings/'),
        ),
    ]
