# Generated by Django 5.2.16 on 2026-09-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_callsession_ai_recording_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyscript',
            name='ai_rules',
            field=models.TextField(blank=True, default='Keep responses short and natural for a phone call. Ask one main question at a time. Do not repeat already collected information. Do not invent fees, schedules, discounts, certificates, guarantees or other facts. If exact information is unavailable, offer human follow-up. Respect refusal immediately and never pressure the customer.', help_text='Behavioral rules the AI must follow.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='company_description',
            field=models.TextField(blank=True, help_text='Short description of the company/institute.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='contact_information',
            field=models.TextField(blank=True, help_text='Phone, WhatsApp, email or other official contact information.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='course_durations',
            field=models.TextField(blank=True, help_text='Available durations. Example: 5 days, 10 days, 15 days, 1 month, 6 months.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='data_to_collect',
            field=models.TextField(blank=True, default='Customer type, education or occupation when relevant, interest area, course interest, level of interest, and callback requirement.', help_text='Information the AI should try to collect naturally.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='frequently_asked_questions',
            field=models.TextField(blank=True, help_text='Verified FAQs and answers the AI is allowed to use.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='key_benefits',
            field=models.TextField(blank=True, help_text='Main benefits/use cases the AI can explain to customers.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='pricing_information',
            field=models.TextField(blank=True, help_text='Only enter verified pricing here. Leave blank if the AI must refer pricing questions to a human.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='products_services',
            field=models.TextField(blank=True, help_text='Courses, programs, products or services the AI is allowed to discuss.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='sales_objective',
            field=models.TextField(blank=True, default="Understand the customer's interest in practical AI training, identify their profile and need, explain the relevant offering, and classify whether they are interested, need more information, are ready to join, or want a callback.", help_text='Main objective of this telecalling campaign.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='tagline',
            field=models.CharField(blank=True, default='Plug into Practical AI.', max_length=200),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Who the service is for. Example: students, working professionals, business owners, educators, creators, parents.'),
        ),
        migrations.AddField(
            model_name='companyscript',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Optional company/team working hours.', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyscript',
            name='bot_name',
            field=models.CharField(default='Brainex AI Assistant', help_text='Name used by the AI caller.', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyscript',
            name='closing_statement',
            field=models.TextField(default='Thank you for your time. If you need more information, our Brainex team can contact you and assist you further.'),
        ),
        migrations.AlterField(
            model_name='companyscript',
            name='company_details',
            field=models.TextField(blank=True, help_text='Legacy / combined company information used by older consumer versions.'),
        ),
        migrations.AlterField(
            model_name='companyscript',
            name='company_name',
            field=models.CharField(default='Brainex AI Institute', max_length=150),
        ),
        migrations.AlterField(
            model_name='companyscript',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Use this configuration for the current AI caller.'),
        ),
        migrations.AlterField(
            model_name='companyscript',
            name='opening_greeting',
            field=models.TextField(default="Hello, I'm the AI calling assistant from Brainex AI Institute. We provide practical AI training programs. May I briefly tell you about them?"),
        ),
    ]
