# Generated by Django 5.2.16 on 2026-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_companyscript_ai_rules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_retention_days', models.PositiveIntegerField(default=5, help_text='Automatically delete customer and AI audio recordings after this many days.')),
                ('automatic_recording_cleanup', models.BooleanField(default=True, help_text='Enable or disable automatic recording cleanup.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
