# Generated by Django 5.2.16 on 2026-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='automatic_recording_cleanup',
            field=models.BooleanField(default=True, help_text='Enable or disable automatic deletion of expired customer and AI call recordings.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='recording_retention_days',
            field=models.PositiveIntegerField(choices=[(1, '1 Day'), (3, '3 Days'), (5, '5 Days'), (7, '7 Days'), (15, '15 Days'), (30, '30 Days'), (60, '60 Days'), (90, '90 Days')], default=5, help_text='Customer and AI response recordings older than this period will automatically be deleted.'),
        ),
    ]
