# Generated by Django 5.2.16 on 2026-09-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_alter_systemsettings_automatic_recording_cleanup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tts_rate',
            field=models.IntegerField(default=1, help_text='AI speech speed. Windows SAPI supports -10 to +10.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tts_voice_name',
            field=models.CharField(blank=True, default='', help_text='Exact installed Windows SAPI voice name. Leave blank when using the system default voice.', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tts_volume',
            field=models.PositiveIntegerField(default=100, help_text='AI speech volume from 0 to 100.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='use_system_default_voice',
            field=models.BooleanField(default=True, help_text='Use the Windows default SAPI voice. Disable this to use the custom voice name entered below.'),
        ),
    ]
