# Generated by Django 5.2.16 on 2026-09-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_systemsettings_tts_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Brainex Female 1', max_length=150, unique=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Other', 'Other')], default='English', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('disabled', 'Disabled')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional notes about this voice.')),
                ('sample_1', models.FileField(blank=True, help_text='Upload WAV or record directly in the browser.', null=True, upload_to='custom_voices/')),
                ('sample_2', models.FileField(blank=True, help_text='Optional additional voice sample.', null=True, upload_to='custom_voices/')),
                ('sample_3', models.FileField(blank=True, help_text='Optional additional voice sample.', null=True, upload_to='custom_voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tts_engine',
            field=models.CharField(choices=[('sapi', 'Windows SAPI'), ('custom', 'Custom Voice')], default='sapi', help_text='Select Windows SAPI or a cloned custom voice.', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='tts_rate',
            field=models.IntegerField(default=-1, help_text='Windows SAPI speech rate from -10 to +10.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='tts_voice_name',
            field=models.CharField(choices=[('Microsoft David Desktop', 'Microsoft David Desktop - Male'), ('Microsoft Zira Desktop', 'Microsoft Zira Desktop - Female')], default='Microsoft Zira Desktop', help_text='Installed Windows SAPI voice.', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='tts_volume',
            field=models.PositiveIntegerField(default=95, help_text='Speech volume from 0 to 100.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='use_system_default_voice',
            field=models.BooleanField(default=False, help_text='Use the Windows default voice instead of selecting one.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='custom_voice',
            field=models.ForeignKey(blank=True, help_text='Select the custom cloned voice when Voice Engine is Custom Voice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings', to='calls.customvoice'),
        ),
    ]
