# Generated by Django 5.2.16 on 2026-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_customvoice_systemsettings_tts_engine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('calls_attempted', models.PositiveIntegerField(default=0)),
                ('calls_completed', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('called_count', models.PositiveIntegerField(default=0)),
                ('follow_up_count', models.PositiveIntegerField(default=0)),
                ('interested_count', models.PositiveIntegerField(default=0)),
                ('not_interested_count', models.PositiveIntegerField(default=0)),
                ('need_more_information_count', models.PositiveIntegerField(default=0)),
                ('ready_to_join_count', models.PositiveIntegerField(default=0)),
                ('callback_requested_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('interest_rate', models.FloatField(default=0)),
                ('follow_up_rate', models.FloatField(default=0)),
                ('ready_to_join_rate', models.FloatField(default=0)),
                ('total_call_duration_seconds', models.PositiveIntegerField(default=0)),
                ('average_call_duration_seconds', models.PositiveIntegerField(default=0)),
                ('previous_day_comparison', models.JSONField(blank=True, default=dict)),
                ('seven_day_comparison', models.JSONField(blank=True, default=dict)),
                ('most_asked_questions', models.JSONField(blank=True, default=list)),
                ('interested_courses', models.JSONField(blank=True, default=list)),
                ('customer_types', models.JSONField(blank=True, default=list)),
                ('education_summary', models.JSONField(blank=True, default=list)),
                ('priority_summary', models.JSONField(blank=True, default=dict)),
                ('follow_up_leads', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('calls_attempted', models.PositiveIntegerField(default=0)),
                ('calls_completed', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('called_count', models.PositiveIntegerField(default=0)),
                ('follow_up_count', models.PositiveIntegerField(default=0)),
                ('interested_count', models.PositiveIntegerField(default=0)),
                ('not_interested_count', models.PositiveIntegerField(default=0)),
                ('need_more_information_count', models.PositiveIntegerField(default=0)),
                ('ready_to_join_count', models.PositiveIntegerField(default=0)),
                ('callback_requested_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('interest_rate', models.FloatField(default=0)),
                ('follow_up_rate', models.FloatField(default=0)),
                ('ready_to_join_rate', models.FloatField(default=0)),
                ('total_call_duration_seconds', models.PositiveIntegerField(default=0)),
                ('average_call_duration_seconds', models.PositiveIntegerField(default=0)),
                ('previous_month_comparison', models.JSONField(blank=True, default=dict)),
                ('daily_performance', models.JSONField(blank=True, default=list)),
                ('most_asked_questions', models.JSONField(blank=True, default=list)),
                ('interested_courses', models.JSONField(blank=True, default=list)),
                ('customer_types', models.JSONField(blank=True, default=list)),
                ('education_summary', models.JSONField(blank=True, default=list)),
                ('system_performance', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_monthly_report')],
            },
        ),
    ]
