"""Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    'django-insecure-i-9o2+8*0@(od6ojs6a!y=%#f!-zagumww1iy!y8d&uz7^8)$o'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','172.20.142.248','192.168.1.21','*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    "unfold",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'calls',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'config.asgi.application'
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.NumericPasswordValidator'
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# 🟢 Media files setup (Audio Recordings, Attachments)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Tell Django to use BigAutoFields (64-bit integers) for all auto-increment IDs globally
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

# 1. Set your local timezone
TIME_ZONE = 'Asia/Kolkata'

# 2. Keep USE_TZ as True so Django stores in UTC but displays in IST
USE_TZ = True

# ============================================================
# UNFOLD ADMIN UI
# ============================================================

UNFOLD = {
    "SITE_TITLE": "Telicall Admin",
    "SITE_HEADER": "Telicall",
    "SITE_SUBHEADER": "AI Calling Management System",
    "DASHBOARD_CALLBACK": "calls.dashboard.dashboard_callback",

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Call Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Call Queue"),
                        "icon": "call",
                        "link": reverse_lazy("admin:calls_callqueueitem_changelist"),
                    },
                    {
                        "title": _("Call Sessions"),
                        "icon": "history",
                        "link": reverse_lazy("admin:calls_callsession_changelist"),
                    },
                    {
                        "title": _("Contacts"),
                        "icon": "contacts",
                        "link": reverse_lazy("admin:calls_contact_changelist"),
                    },
                    {
                        "title": _("Sales Insights"),
                        "icon": "psychology",
                        "link": reverse_lazy("admin:calls_salesinsight_changelist"),
                    },
                ],
            },
            {
                "title": _("Reports"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Telicall Reports"),
                        "icon": "analytics",
                        "link": reverse_lazy("admin:calls_callqueueitem_reports"),
                    },
                ],
            },
            {
                "title": _("AI Configuration"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Company Scripts"),
                        "icon": "description",
                        "link": reverse_lazy("admin:calls_companyscript_changelist"),
                    },
                    {
                        "title": _("Custom Voices"),
                        "icon": "record_voice_over",
                        "link": reverse_lazy("admin:calls_customvoice_changelist"),
                    },
                    {
                        "title": _("System Settings"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:calls_systemsettings_changelist"),
                    },
                ],
            },
        ],
    },
}

